<?php 
    if (count($this->flashMessages) > 0) {
        echo '<div class="has-error"><ul>';
        foreach ($this->flashMessages as $msg)  {
            echo '<li>'.$msg.'</li>';
        }
        echo '</ul></div>';
    }
    
    echo $this->messages;
?>
<strong>Module:</strong>        Market &raquo;
<strong>Controller:</strong>    IndexController &raquo;
<strong>Action:</strong>        index
